import { IMAGE_META } from '../generated/image-meta';

type Props = {
  /** Local image stem (e.g. "5011") or an external http(s) URL. */
  image: string;
  /** Question number, used for alt text. */
  number: number;
  class?: string;
};

/**
 * Renders a quiz illustration using <picture> with AVIF + WebP sources and a
 * JPEG fallback, carrying srcset / sizes for responsive delivery.
 *
 * For external URLs the element falls back to a plain <img>.
 * width + height are injected from the generated IMAGE_META map so the browser
 * can reserve the correct space before the image loads (no CLS).
 *
 * Outputs served from public/images/ are generated by:
 *   npm run process-images
 */
export function QuizImage({ image, number, class: cls }: Props) {
  const alt = `Ilustrasi soal ${number}`;

  // External URL — render a plain img, no picture/srcset needed
  if (/^https?:\/\//i.test(image)) {
    return (
      <img
        src={image}
        alt={alt}
        loading="lazy"
        decoding="async"
        class={cls}
      />
    );
  }

  // Local image — build paths from stem and look up dimensions
  const meta = IMAGE_META[image];
  const w = meta?.[0];
  const h = meta?.[1];

  // Prefix with Vite's base URL so paths work regardless of deployment sub-path
  // (e.g. base = "/gentsuki-ready-web/" → "/gentsuki-ready-web/images/5011.avif")
  const base = (import.meta.env.BASE_URL ?? '/').replace(/\/$/, '');
  const path = `${base}/images/${image}`;

  return (
    <picture>
      {/* AVIF: best compression, widest browser support since 2022 */}
      <source
        type="image/avif"
        srcset={`${path}.avif 960w, ${path}-sm.avif 480w`}
        sizes="(max-width: 540px) calc(100vw - 1.8rem), 672px"
      />
      {/* WebP: universal fallback for browsers without AVIF */}
      <source
        type="image/webp"
        srcset={`${path}.webp 960w, ${path}-sm.webp 480w`}
        sizes="(max-width: 540px) calc(100vw - 1.8rem), 672px"
      />
      {/* JPEG: final fallback (IE, very old Safari) */}
      <img
        src={`${path}.jpg`}
        alt={alt}
        width={w}
        height={h}
        loading="lazy"
        decoding="async"
        class={cls}
      />
    </picture>
  );
}
